### PR TITLE
refactor(cmd): Update doc for secret key option in create cmd

### PR DESCRIPTION
**Pull request by Quentinchampenois**
## Description

Hello! this is a very light PR as I am just discovering this project.

I noticed a typo in the `secret-key` description for the `create` command, this PR just update this description.

Thank you for this nice project !
 
## How Has This Been Tested?

Confirmed the new description by running `go run . help create`

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [ ] read the [CONTRIBUTION](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

## Note 

Also the link in PR Template is no longer available : [CONTRIBUTION](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md) guide

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @Quentinchampenois 

Thanks for the interest.

I was just curious why you sent this particular PR, I don't recognise you as an inlets subscriber?

Alex

**Comment by Quentinchampenois** [comment]
Hello @alexellis , 

No I am not, I just discovered the project while reading your blog about k3s on raspberry pi, because I noticed the typo in help command I suggested the edit. 

If you are open to contributions I might be interested to contribute in the future

**Comment by alexellis** [comment]
The contribution is fine, and open to them.

I was just curious as I didn't understand the motivation. Thanks for explaining. 

Arkade - https://github.com/alexellis/arkade has more opportunties to contribute, and perhaps https://github.com/openfaas/faas-cli

If you use or have used Kubernetes, check out [k3sup](https://github.com/alexellis/k3sup) and my newest project: [kubetrim](https://github.com/alexellis/kubetrim) which might have the odd opportunity to contribute.

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
This same change may apply in other commands if you want to look, i.e. delete?

**Pull request merged**
