### PR TITLE
AWS: Update Image to Ubuntu 20_04

### PR DESCRIPTION
**Pull request by cpanato**
## Description
Update ubuntu image to use 20.04

Main issue: https://github.com/inlets/inletsctl/issues/95

## How Has This Been Tested?
- made the change
- build inletsctl
- run

```shell
$ ./bin/inletsctl-darwin create --provider=ec2 -a honk! --secret-key=honk_secret -r us-east-1 --vpc-id=vpc-0xxxxxa --subnet-id=subnet-0xxxx9

Using provider: ec2
Requesting host: pensive-villani8 in us-east-1, from ec2
Host: i-05ce986e0fd809285, status: creating
....
[97/500] Host: i-05ce986e0fd809285, status: initialising
[98/500] Host: i-05ce986e0fd809285, status: active
inlets PRO TCP (0.8.7) server summary:
  IP: 54.163.14.195
  Auth-token: Q1YdEeQ4mwTfjJneDZNif7zNiM21dddddJ4mVEH0PUnHpDarU5wuJjE3C

Command:

# Obtain a license at https://inlets.dev
# Store it at $HOME/.inlets/LICENSE or use --help for more options
export LICENSE="$HOME/.inlets/LICENSE"

# Give a single value or comma-separated
export PORTS="8000"

# Where to route traffic from the inlets server
export UPSTREAM="localhost"

inlets-pro tcp client --url "wss://54.163.14.195:8123" \
  --token "Q1YdEeQ4mwTfjJneDZNidddddDJ4mVEH0PUnHpDarU5wuJjE3C" \
  --upstream $UPSTREAM \
  --ports $PORTS

To delete:
  inletsctl delete --provider ec2 --id "i-05ce986e0fd809285"
```

Screenshot 2021-07-27 at 13 39 42

connecting
```
$ inlets-pro tcp client --url "wss://3.82.226.90:8123" \
  --token "AEzByv91d4YrptV1lhk5xxxxxxqxtTmeaMNMUGsZgO7dhl9hEKa"  \
  --upstream $UPSTREAM \
  --ports $PORTS --license "xxxxxxxx"
2021/07/27 15:28:53 Starting TCP client. Version 0.8.7 - 9a7a04c85f25d2400359536965a971146aae72f0
2021/07/27 15:28:53 Licensed to: Carlos Panato <ctadeu@gmail.com>, expires: 21 day(s)
2021/07/27 15:28:53 Upstream server: localhost, for ports: 8000
inlets-pro client. Copyright OpenFaaS Ltd 2021
INFO[2021/07/27 15:28:53] Connecting to proxy                           url="wss://3.82.226.90:8123/connect"
INFO[2021/07/27 15:28:54] Connection established.. OK.
```

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] read the [CONTRIBUTION](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
We'll need to validate that it works with a client. If your trial has expired, DM me on Slack

**Comment by cpanato** [comment]
E2E test is working! thanks @alexellis for the temp license

**Review by alexellis — APPROVED** [review]
LGTM

**Comment by dirien** [comment]
Fixes issue #108

**Pull request merged**
