### PR TITLE
Detail install to local directory vs. global in README

### PR DESCRIPTION
**Pull request by mbacchi**
Signed-off-by: Matt Bacchi <mbacchi@gmail.com>

## How Has This Been Tested?

Add more detail to documentation to describe how to install to a local directory vs. global /usr/local/bin location. This mirrors the documentation in the [inlets README](https://github.com/inlets/inlets/blob/master/README.md#install-the-cli).

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
We have a few open issues, do you feel like taking any of them up? Some Golang skills required

**Comment by mbacchi** [comment]
> We have a few open issues, do you feel like taking any of them up? Some Golang skills required

I do see that there are a few. At the moment I'm just getting familiar with the tool, haven't played with it before now. Then I'll consider looking at some of them, I immediately noticed there was an EC2 provider, but not an AWS LightSail provider. Maybe I'll look into adding that. I haven't done anything beyond basic tutorials in Golang but I should be able to pick it up fairly quickly.

**Comment by alexellis** [comment]
How about https://github.com/inlets/inletsctl/issues/47 ?

**Comment by mbacchi** [comment]
> How about #47 ?

I had a fix ready to go just now, and then noticed @kadern0 beat me to it.

As an aside, regarding the doc change in this PR, I left what I thought was overly verbose usage of the raw githubusercontent URL in place. I would have removed that but wanted to respect what was there. I think it should be removed and just point to the inletsctl.inlets.dev url. If you want to do this I also think we should still include the local/global options for folks who don't want to install it to their system directories.

**Pull request merged**
